name: 5amSunrises
favicon: null
layout_spectrum: 0.06699
typography_spectrum: 0.25746
title: 5am Sunrises
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3c293c'
    - '#87608e'
    - '#f4a844'
    - '#f4d8bb'
    - '#8bb297'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
