name: 5amSunrises
favicon: null
layout_spectrum: 0.88304
typography_spectrum: 0.25746
title: 5am Sunrises
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3c293c'
    - '#87608e'
    - '#f4a844'
    - '#f4d8bb'
    - '#8bb297'
  brandStrength: 0.6875
  lightness: 0.5951776260044426
  saturation: 0.668715852778405
  rhythmicContrast: 0.3424562804866582
purpose: []
